apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "ibm-aiops-pvc"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
